#!/bin/bash

#sudo bash deploy_croto.sh IP_MASTER PUERTO_MASTER PUERTO_MASTER_DESALOJO IP_STORAGE PUERTO_STORAGE LOG_LEVEL (En el futuro)

IP_MASTER=127.0.0.1
PUERTO_MASTER=9004
PUERTO_MASTER_DESALOJO=9005

IP_STORAGE=127.0.0.1
PUERTO_STORAGE=9002

LOG_LEVEL=DEBUG #DEBUG INFO


dir_query='./query_control'
dir_master='./master'
dir_storage='./storage'
dir_worker='./worker'

dir_montaje='../../storage'
dir_queries='../queries'


echo "IP_MASTER=${IP_MASTER}"
echo "PUERTO_MASTER=${PUERTO_MASTER}"
echo "PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}"
echo "IP_STORAGE=${IP_STORAGE}"
echo "PUERTO_STORAGE=${PUERTO_STORAGE}"
echo "LOG_LEVEL=${LOG_LEVEL}"



#QUERY_CONTROL

#query.config
echo "
IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_query}/query.config"


#MASTER

#master_plani_fifo.config
echo "PUERTO_ESCUCHA=${PUERTO_MASTER}
ALGORITMO_PLANIFICACION=FIFO
TIEMPO_AGING=500
LOG_LEVEL=${LOG_LEVEL}" > "${dir_master}/master_plani_fifo.config"


#master_plani_priori.config
echo "PUERTO_ESCUCHA=${PUERTO_MASTER}
ALGORITMO_PLANIFICACION=PRIORIDADES
TIEMPO_AGING=500
LOG_LEVEL=${LOG_LEVEL}" > "${dir_master}/master_plani_priori.config"


#P_errores.config
echo "PUERTO_ESCUCHA=${PUERTO_MASTER}
ALGORITMO_PLANIFICACION=FIFO
TIEMPO_AGING=0
LOG_LEVEL=${LOG_LEVEL}" > "${dir_master}/P_errores.config"


#P_general.config
echo "PUERTO_ESCUCHA=${PUERTO_MASTER}
ALGORITMO_PLANIFICACION=PRIORIDADES
TIEMPO_AGING=25
LOG_LEVEL=${LOG_LEVEL}" > "${dir_master}/P_general.config"


#P_memoria_worker.config
echo "PUERTO_ESCUCHA=${PUERTO_MASTER}
ALGORITMO_PLANIFICACION=FIFO
TIEMPO_AGING=0
LOG_LEVEL=${LOG_LEVEL}" > "${dir_master}/P_memoria_worker.config"



#P_planificacion.config
echo "PUERTO_ESCUCHA=${PUERTO_MASTER}
ALGORITMO_PLANIFICACION=FIFO
TIEMPO_AGING=500
LOG_LEVEL=${LOG_LEVEL}" > "${dir_master}/P_planificacion.config"


#P_storage.config
echo "PUERTO_ESCUCHA=${PUERTO_MASTER}
ALGORITMO_PLANIFICACION=PRIORIDADES
TIEMPO_AGING=0
LOG_LEVEL=${LOG_LEVEL}" > "${dir_master}/P_storage.config"


#STORAGE

#P_errores.config
echo "PUERTO_ESCUCHA=${PUERTO_STORAGE}
FRESH_START=FALSE
PUNTO_MONTAJE=${dir_montaje}
RETARDO_OPERACION=50
RETARDO_ACCESO_BLOQUE=50

FS_SIZE=65536
BLOCK_SIZE=16

LOG_LEVEL=${LOG_LEVEL}" > "${dir_storage}/P_errores.config"

#P_general.config
echo "PUERTO_ESCUCHA=${PUERTO_STORAGE}
FRESH_START=FALSE
PUNTO_MONTAJE=${dir_montaje}
RETARDO_OPERACION=100
RETARDO_ACCESO_BLOQUE=10

FS_SIZE=65536
BLOCK_SIZE=16

LOG_LEVEL=${LOG_LEVEL}" > "${dir_storage}/P_general.config"


#P_memoria_worker.config
echo "PUERTO_ESCUCHA=${PUERTO_STORAGE}
FRESH_START=TRUE
PUNTO_MONTAJE=${dir_montaje}
RETARDO_OPERACION=25
RETARDO_ACCESO_BLOQUE=25

FS_SIZE=65536
BLOCK_SIZE=16

LOG_LEVEL=${LOG_LEVEL}" > "${dir_storage}/P_memoria_worker.config"



#P_planificacion_FRESH.config
echo "PUERTO_ESCUCHA=${PUERTO_STORAGE}
FRESH_START=TRUE
PUNTO_MONTAJE=${dir_montaje}
RETARDO_OPERACION=25
RETARDO_ACCESO_BLOQUE=25

FS_SIZE=65536
BLOCK_SIZE=16

LOG_LEVEL=${LOG_LEVEL}" > "${dir_storage}/P_planificacion_FRESH.config"


#P_planificacion_NO_FRESH.config
echo "PUERTO_ESCUCHA=${PUERTO_STORAGE}
FRESH_START=FALSE
PUNTO_MONTAJE=${dir_montaje}
RETARDO_OPERACION=25
RETARDO_ACCESO_BLOQUE=25

FS_SIZE=65536
BLOCK_SIZE=16

LOG_LEVEL=${LOG_LEVEL}" > "${dir_storage}/P_planificacion_NO_FRESH.config"


#P_storage.config
echo "PUERTO_ESCUCHA=${PUERTO_STORAGE}
FRESH_START=FALSE
PUNTO_MONTAJE=${dir_montaje}
RETARDO_OPERACION=50
RETARDO_ACCESO_BLOQUE=50

FS_SIZE=65536
BLOCK_SIZE=16

LOG_LEVEL=${LOG_LEVEL}" > "${dir_storage}/P_storage.config"


#storage_plani.config
echo "PUERTO_ESCUCHA=${PUERTO_STORAGE}
FRESH_START=FALSE
PUNTO_MONTAJE=${dir_montaje}
RETARDO_OPERACION=25
RETARDO_ACCESO_BLOQUE=25

FS_SIZE=40960
BLOCK_SIZE=128

LOG_LEVEL=${LOG_LEVEL}" > "${dir_storage}/storage_plani.config"


#WORKER

#P_errores.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=256
RETARDO_MEMORIA=25
ALGORITMO_REEMPLAZO=LRU
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_errores.config"


#P_general_1.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=128
RETARDO_MEMORIA=10
ALGORITMO_REEMPLAZO=LRU
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_general_1.config"


#P_general_2.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=256
RETARDO_MEMORIA=5
ALGORITMO_REEMPLAZO=CLOCK-M
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_general_2.config"


#P_general_3.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=64
RETARDO_MEMORIA=15
ALGORITMO_REEMPLAZO=CLOCK-M
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_general_3.config"


#P_general_4.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=96
RETARDO_MEMORIA=15
ALGORITMO_REEMPLAZO=LRU
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_general_4.config"


#P_general_5.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=160
RETARDO_MEMORIA=10
ALGORITMO_REEMPLAZO=LRU
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_general_5.config"


#P_general_6.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=192
RETARDO_MEMORIA=15
ALGORITMO_REEMPLAZO=CLOCK-M
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_general_6.config"


#P_memoria_worker.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=48
RETARDO_MEMORIA=25
ALGORITMO_REEMPLAZO=CLOCK-M
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_memoria_worker.config"


#P_planificacion_1.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=1024
RETARDO_MEMORIA=50
ALGORITMO_REEMPLAZO=LRU
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_planificacion_1.config"

#P_planificacion_2.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=1024
RETARDO_MEMORIA=50
ALGORITMO_REEMPLAZO=CLOCK-M
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_planificacion_2.config"


#P_storage.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=128
RETARDO_MEMORIA=25
ALGORITMO_REEMPLAZO=LRU
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/P_storage.config"

#worker_plani_1.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=1024
RETARDO_MEMORIA=50
ALGORITMO_REEMPLAZO=LRU
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/worker_plani_1.config"


#worker_plani_2.config
echo "IP_MASTER=${IP_MASTER}
PUERTO_MASTER=${PUERTO_MASTER}
PUERTO_MASTER_DESALOJO=${PUERTO_MASTER_DESALOJO}
IP_STORAGE=${IP_STORAGE}
PUERTO_STORAGE=${PUERTO_STORAGE}

TAM_MEMORIA=1024
RETARDO_MEMORIA=50
ALGORITMO_REEMPLAZO=LRU
PATH_SCRIPTS=${dir_queries}
LOG_LEVEL=${LOG_LEVEL}" > "${dir_worker}/worker_plani_2.config"
